// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjlwuplnfzwjkhdofxyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqbHd1cGxuZnp3amtoZG9meHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzM1NzksImV4cCI6MjA1MTIwOTU3OX0.Lp1ybqIfmitTl7IXLiMtPAsrAbapdUzbC9BGBUdm7f8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);